### ISSUE TITLE
wait-for-gitfs does not appear to work (?)

### ISSUE THREAD

**Issue by danielrichman** [adamgreig/saltbot#10]
I pushed, and it very quickly started the highstate. It did not apply the most recent commit: I had to wait and ask it to highstate again

http://saltbot.habhub.org/jobs/20150121135046722687
http://saltbot.habhub.org/jobs/20150121135123191041
http://saltbot.habhub.org/jobs/20150121135209483184

**Comment by adamgreig** [comment]
race is because gitfs fires the event after it finishes updating the filesystem; if you push while it's still processing then it'l finish processing the (outdated) update and saltbot deploys.

Need to either check the actual commit on the checked out gitfs in /var/cache/salt/master/gitfs or need to just wait for two gitfs update events.
